### ISSUE TITLE
FormEditor breaks on Firefox

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/form-js#911] opened 2023-11-23 14:49 UTC
### Describe the Bug

The Form editor breaks during initialization.

Reported by @sbuettner on Slack: https://camunda.slack.com/archives/CKGH9LR40/p1700653964903659

### Steps to Reproduce

1. Open https://demo.bpmn.io/form/s/start in firefox
2. Reload a few times if needed
3. Drag a new element into the form
4. The integration breaks

### Expected Behavior

The editor works with firefox

### Additional Information
![image](https://github.com/bpmn-io/form-js/assets/21984219/56f65743-8c4e-4bd3-9b48-e8e71b1783e6)
Even though the Stack says this breaks in EventBus, this is most likely due to broken source maps. I confirmed with non-mapped code that it fails in this useState statement.
https://github.com/bpmn-io/form-js/blob/752e8fb33d0a347209b4bff750418ac3d4094a18/packages/form-js-editor/src/render/components/FormEditor.js#L316

I was not able to debug it any further, as I was not able to reproduce consistently without a MacOS system.

### Environment

- Host (Browser/Node version), if applicable: Firefox 120.0
- OS: MacOS
- Library version: 1.4.0

**Comment by vsgoulart** [comment] 2023-11-23 15:21
@marstamm To me it happened more consistently when dragging a new form element after the first reload
Updated the description to include that

**Comment by vsgoulart** [comment] 2024-01-11 16:09
@marstamm I'm closing this since I wasn't able to reproduce it anymore, please reopen and ping me if still happens or anyone else complains about it

**Closed by vsgoulart** 2024-01-11 16:09 UTC
Labels: bug, backlog
