### ISSUE TITLE
Form components disappear after moving them around in a row following preact 10.16.x update

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#1057] opened 2024-02-19 19:16 UTC
### Describe the Bug

Form components disappear after moving them around in a row .

### Steps to Reproduce

1. Add components into some rows.
2. Drag components from one row into another.
3. Occasionally, components start to disappear. Once that happened, they continue to disappear on every drag, and require the form to re-render to appear again.

See videos:

https://github.com/bpmn-io/form-js/assets/56470362/c8612d99-9501-4f25-a7e8-53276404ed4d

https://github.com/bpmn-io/form-js/assets/56470362/105ff85d-a874-4550-8859-807a67a9b901

### Expected Behavior

Components never disappear after dragging.

### Environment

- form-js v1.7

**Comment by marcosgvieira** [comment] 2024-03-04 14:47
@Skaiir can you please update the status on this one?

**Comment by Skaiir** [comment] 2024-03-06 05:26
So there's two aspects of this bug. This is an old bug that resurfaced due to preact getting upgraded in the web modeler somehow.

The issue is as follows:
- Preact moves components around when it re-renders
- Dragula moves divs around as well
- The combination of the two causes problems with preact's diffing algorithm which causes it to delete the new element entirely in some circumstances

How to fix:
- in web modeler, short term, restrict preact to a compatible version, we already have the restriction in this library but it seems the web modeler doesn't care and still enforces the older version
- here, long term, change the way our drag and drop works, which means not moving elements around at all and let preact handle the moving instead, which I started to tackle with https://github.com/bpmn-io/form-js/issues/1058 until we deprioritized

**Comment by Skaiir** [comment] 2024-03-06 05:32
There is also this issue which tracks the same problem:

https://github.com/bpmn-io/form-js/issues/760

**Comment by Skaiir** [comment] 2024-03-06 08:10
Some updates here, the reason why the bug resurfaced in web modeler was that our preact version restricting was yarn specific, and wasn't updated during the change to npm. I have a fix for this on web modeler [here](https://github.com/camunda/web-modeler/pull/8432)

**Comment by Skaiir** [comment] 2024-03-06 11:33
Temporarily fixed via https://github.com/camunda/web-modeler/commit/b4cd239b943b75cd2359cdf56fde24c34682ec89, I will close this issue and use the older one for future reference.

**Closed by Skaiir** 2024-03-06 11:33 UTC
Labels: bug, needs review

**Comment by Ken-Scofield** [comment] 2024-07-03 01:19
mark
