### ISSUE TITLE
Styling issues for rendered markdown

### ISSUE THREAD

**Issue by andreasgeier** [bpmn-io/form-js#87] opened 2021-06-17 09:24 UTC
__Describe the Bug__

There exists a number of minor styling issues for markdown rendering:

* [x] `<br />` tags are inserted, preventing a proper paragraph layout :arrow_right: users should be able to structure text in multiple paragraphs (https://github.com/bpmn-io/form-js/pull/93)
* [x] **Demo only:** ~~links are not underlined :arrow_right: should be underlined~~
* [x] Images are placed in original size which may break the form layout :arrow_right: should apply a maximum width to images so that these do not break the layout (https://github.com/bpmn-io/form-js/pull/92)
* [x] Inconsistent spacing between paragraphs and lists :arrow_right: should have consistent spacing. (https://github.com/bpmn-io/form-js/pull/93)
* [ ] Unordered and ordered lists have different spacing on the left :arrow_right: should be aligned

__Steps to Reproduce__

- Open the [form-js demo](https://demo.bpmn.io/form)
- Open [test.form file](https://github.com/bpmn-io/form-js/files/6675309/text.form.txt)
- Enter markdown in textarea on properties panel to see the results mentioned in the bug description

__Expected Behavior__

See above.

__Context__

For reference a screenshot highlighting above issues:

![image](https://user-images.githubusercontent.com/58601/122523812-ba19a480-d017-11eb-96be-2fd025b9bd51.png)

---

For reference a screenshot with a HTML page:

![image](https://user-images.githubusercontent.com/58601/122526414-8f7d1b00-d01a-11eb-9525-3fdaa467adc7.png)

**Comment by nikku** [comment] 2021-06-17 12:48
For reference could you share the form file you used to reproduce this?

**Comment by andreasgeier** [comment] 2021-06-17 15:00
> For reference could you share the form file you used to reproduce this?

No, sorry. I hacked that using the form-js demo and the sandbox. But each topic is very easy to reproduce with just a small snippet of markdown.

**Comment by nikku** [comment] 2021-06-17 15:44
I'll take this as an opportunity to add a preview to our demo, and provide a diagram that allows us to reproduce the issue.

**Comment by nikku** [comment] 2021-06-18 07:52
Was able to reproduce most issues.

**Comment by nikku** [comment] 2021-06-18 08:18
@andreasgeier I've added plain HTML starters that allow you to use form-js in a raw manner: https://github.com/bpmn-io/form-js-examples/pull/1. The link styling issue you raised is due to style overrides in the bpmn.io demo (nothing form-js can do about it).

Will follow up with a preview on the demo, at some point.

**Comment by nikku** [comment] 2021-06-18 09:50
We were able to close most of these issues, as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/58601/122542592-294cc400-d02b-11eb-860c-497a3496da9d.png).

**Comment by nikku** [comment] 2021-06-18 11:02
Closing this one as most issues have been addressed with https://github.com/bpmn-io/form-js/pull/93 merged.

Please open a follow up issue for the remaining open topics, if you deem them important.

**Closed by nikku** 2021-06-18 11:02 UTC
Labels: bug, editor, ready, viewer

**Comment by nikku** [comment] 2021-06-18 11:07
No follow up on the alignment is needed. It is _demo only_, too as you can see in the screenshot above :arrow_up:.
