### ISSUE TITLE
Form keys defined with `.` syntax should map to nested instance variables

### ISSUE THREAD

**Issue by upgradingdave** [bpmn-io/form-js#769] opened 2023-08-10 19:49 UTC
### Is your feature request related to a problem? Please describe.

In Camunda 8 input and output mappings, when I enter a Process Variable Name of `google.clientId` and a value of `foo`, this is mapped into a process instance variable that looks like this: 

```json
{
  "google":  {
    "clientId" : "foo"
  }
}
```

However, when I use a similar approach in form builder, if I enter `google.clientId` for a form key, and a value of `foo`, it's mapped into a process variable that looks like this: 

```json
{
  "google.clientId": "foo"
}
```

Is it possible to implement so that form builder key mappings behave the same as input/output variable mappings?

### Describe the solution you'd like

If I `google.clientId` for a form key, and a value of `foo`, it'd be great if it were mapped into a process variable that looks like this: 

```json
{
  "google":  {
    "clientId" : "foo"
  }
}
```

### Describe alternatives you've considered

A work around is to use output mappings in the script task to map form keys into a nested structure. But this seems redundant?

### Additional context
Here's a screenshot. 
<img width="1669" alt="Screen Shot 2023-08-10 at 3 36 27 PM" src="https://github.com/bpmn-io/form-js/assets/939229/d0a5e53e-3465-46de-9eb5-cde080502966">

Would it be possible to change so that the `Form Output` shows this instead?

```json
{
  "google":  {
    "clientId" : "secrets.googleClientId",
    "accessToken": "secrets.googleAccessToken",
    "refreshToken": "secrets.googleRefresToken",
    "projectId": "camunda-researchanddevelopment",
    "clusterId": "your-name-cluster"
    "zoneId": "us-central1-a"
  },
  "secrets": {
    "GCP_OAUTH2_CLIENT_SECRET": "secrets.GCP_OAUTH2_CLIENT_SECRET"
  }
}
```

**Comment by vsgoulart** [comment] 2023-08-11 08:26
@Skaiir This will be possibly included in the subforms topics, right?

**Comment by Skaiir** [comment] 2023-08-11 09:27
@upgradingdave 

Thanks for raising this in the issues, I'll have to close it as a dupe of https://github.com/bpmn-io/form-js/issues/464 though. 
I'm currently working on this as part of this epic: https://github.com/bpmn-io/form-js/issues/767. 

I think we can realistically see this implemented in the next couple of weeks, if everything goes smoothly :)

**Closed by Skaiir** 2023-08-11 09:27 UTC
Labels: enhancement
