### ISSUE TITLE
Date picker calendar icon sticks to the right in Carbon styles

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#1053] opened 2024-02-16 13:19 UTC
### Describe the Bug

The calendar icon in the date picker sticks to the right in Carbon styles

<img width="493" alt="Bildschirmfoto 2024-02-16 um 14 19 13" src="https://github.com/bpmn-io/form-js/assets/56470362/e9b4b842-b0ae-455e-96d5-55b0f93640e1">

### Steps to Reproduce

Add date picker to a group that fits half the form

### Expected Behavior

Icon has proper padding to the right

### Environment

- Library version: v1.7.0

**Comment by vsgoulart** [comment] 2024-04-10 20:03
@christian-konrad @Skaiir I can't reproduce this anymore, I think we can close it

**Comment by christian-konrad** [comment] 2024-04-17 08:30
@vsgoulart @Skaiir no, it's still there on 8.5

![Image](https://github.com/bpmn-io/form-js/assets/56470362/0361e54c-fab7-4437-b529-8638d24c3e44)

**Comment by marcosgvieira** [comment] 2024-09-06 13:28
Not able to reproduce on latest 8.5 version:


![Image](https://github.com/user-attachments/assets/55fa5d30-c78a-484d-8d7f-f585dadb52d3)

**Closed by marcosgvieira** 2024-09-06 13:28 UTC
Labels: bug, backlog
