### ISSUE TITLE
Create empty state for the editor

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#441] opened 2022-11-30 09:40 UTC
__What should we do?__

Follow up on https://github.com/camunda/team-hto/issues/81:

Create an encouraging empty state for the form editor, that makes clear where the drop target is (on the editor, not the preview).

__Why should we do it?__

The current one in Web Modeler is broken https://github.com/camunda/web-modeler/issues/3084, since it is just hacky.
It might be better to not be implemented by Web Modeler, but by our team.

![image](https://user-images.githubusercontent.com/56470362/204761246-34df0c7a-a17c-4fd1-8aa7-fae82e763912.png)

**Comment by pinussilvestrus** [comment] 2023-07-18 12:45
I believe this is a duplicate of https://github.com/bpmn-io/form-js/issues/336

**Closed by pinussilvestrus** 2023-07-18 12:45 UTC
Labels: enhancement, good first issue, backlog, spring cleaning, ux
